jwt:
  authoritiesKey: auth
  #密钥 KEY
  secret: 3f*F5tc6azCB@Ur*3g
  # HeaderKEY
  tokenHeader: TOKEN
  # jwt过期时间 单位秒 1天后过期=86400 7天后过期=60480
  expiration: 1800
  # 放入redis过期时间 单位秒 1天后过期=86400 7天后过期=604800
  redisExpiration: 1800



